navigation:
- text: Home
  url: /Helveticolor/
- text: Help
  url: /Helveticolor/help.html
- text: Release Notes
  url: /Helveticolor/release_notes.html
- text: Download
  url: http://google.com/foo.zip
  layout: default