navigation:
- text: Home
  url: /index.html
- text: Help
  url: /help.html
- text: Release Notes
  url: /release_notes.html
- text: Download
  url: http://google.com/foo.zip
  is_download: true
layout: default